<a href="https://colab.research.google.com/github/JAntonioRosales/CE888-Data-Science/blob/main/labs/lab_1/Lab1_myNotebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Question 1

Write a function list_to_array that receives a list as a function and returns the list converted into a numpy array.

In [ ]:
import numpy as np

def list_to_array(myList):
    array = np.asarray(myList)
    return array

In [ ]:
print(list_to_array([1, 2, 3, 4, 5]))

[1 2 3 4 5]


### Question 2

Using numpy, write a function called 'min', which takes an array or list of numbers as input and returns the minimum value found in them.

In [ ]:
import numpy as np

def min(numbers):
    minVal = np.amin(numbers)
    return minVal

In [ ]:
mark2 = [55,88,78,90,79,94, 3210]
print('%d' % min(mark2))

55


### Question 3

Using numpy, write a function called 'percentile', which takes as input an array or list of numbers and a number between 0-1 (the percentile that the user wants to calculate) and returns the percentile.

In [ ]:
import numpy as np

def percentile(numbers, perc):
    p = np.percentile(numbers, perc*100)
    return p

In [ ]:
mark2 = [55, 88, 78, 90, 79, 94, 3210]
print('%.2f' % percentile(mark2, 0.4))

82.60


### Question 4

In [ ]:
import numpy as np

def sorting_inv(numbers):
    sorted = np.sort(numbers)[::-1]
    return sorted

In [ ]:
mark2 = [55, 88, 78, 90, 79, 94, 3210]
print('%d' % sorting_inv(mark2)[0])

3210


### Question 5

Using numpy, write a function called 'percentile_array_columns', which takes as input a 2D array of numbers and a percentile (number between 0-100) and returns the column-wise percentiles of the array.

In [ ]:
import numpy as np

def percentile_array_columns(myArray, perc):
    perList = []
    shape = myArray.shape
    for i in range(shape[1]):
        col = myArray[:,i]
        p = np.percentile(col, perc)
        perList.append(p)
    return perList

In [ ]:
mark2 = np.asarray([55, 88, 78, 90, 79, 94]).reshape(2, -1)
per = percentile_array_columns(mark2, 60)
print('%.2f, %.2f' % (per[0], per[1]))

76.00, 84.40


Some tinkering...

In [ ]:
import numpy as np

mark1 = np.asarray([55, 88, 78, 90, 79, 94]).reshape(1, -1)
mark1

array([[55, 88, 78, 90, 79, 94]])

In [ ]:
mark2 = np.asarray([55, 88, 78, 90, 79, 94]).reshape(2, -1)
mark2

array([[55, 88, 78],
       [90, 79, 94]])

In [ ]:
mark3 = np.asarray([55, 88, 78, 90, 79, 94]).reshape(3, -1)
mark3

array([[55, 88],
       [78, 90],
       [79, 94]])

In [ ]:
shape=mark2.shape

In [ ]:
for i in range(shape[1]):
  col = mark2[:,i]
  print(col)

[55 90]
[88 79]
[78 94]


In [ ]:
for row in mark2:
  print(row)

[55 88 78]
[90 79 94]


### Question 6

Using numpy, write a function called 'mean_of_array_columns', which takes as input a 2D array of numbers and returns the column-wise averages of the array.

In [ ]:
import numpy as np

def mean_of_array_columns(numbers):
    mean = np.mean(numbers, axis=0)
    return mean

In [ ]:
mark2 = np.asarray([55, 88, 78, 90, 79, 94]).reshape(2, -1)
print('%d' % mean_of_array_columns(mark2).shape[0])

3


Some tinkering...

In [ ]:
mark2 = np.asarray([55, 88, 78, 90, 79, 94]).reshape(2, -1)
shape = mark2.shape
mark2

array([[55, 88, 78],
       [90, 79, 94]])

In [ ]:
import numpy as np

def mean_of_array_columns(numbers):
    shape = mark2.shape
    

In [ ]:
mark2 = np.asarray([55, 88, 78, 90, 79, 94]).reshape(2, -1)
print('%d' % mean_of_array_columns(mark2).shape[0])

### Question 7

We're going to use numpy to generate random numbers. Check the documentation for numpy.random.choice() to complete the functions below.

NOTE: it's important that you pass the parameters to np.random.choice in order. For example, if the instructions say 'return A with probability A1 and B with probability B1', you should pass the arguments to np.random.choice as np.random.choice([A, B], p=[A1, B1]) to be marked correctly.

In [ ]:
import numpy as np

# Define our actions

def action_0():
    ''' This should return 1 with probability 50%, and 0 with probability 50%'''
    rand = np.random.choice([1, 0], p=[0.5, 0.5])
    return rand

def action_1():
    ''' This should return 1 with probability 60%, and 0 with probability 40%'''
    rand = np.random.choice([1, 0], p=[0.6, 0.4])
    return rand

def action_2():
    ''' This should return 1 with probability 20%, and 0 with probability 80%'''
    rand = np.random.choice([1, 0], p=[0.2, 0.8])
    return rand

In [ ]:
np.random.seed(4)
print('%d, %d, %d, %d, %d, %d' % (action_0(), action_1(), action_2(), action_0(), action_1(), action_2()))

0, 1, 0, 0, 0, 0


### Question 8

We're going to use numpy to generate random numbers. Check the documentation for numpy.random.choice() to complete the functions below.

NOTE: it's important that you pass the parameters to np.random.choice in order. For example, if the instructions say 'return A with probability A1 and B with probability B1', you should pass the arguments to np.random.choice as np.random.choice([A, B], p=[A1, B1]) to be marked correctly.

In [ ]:
import numpy as np

# Define our actions

def policy():
    ''' This should return 0, 1, or 2 with equal probabilities '''
    rand = np.random.choice([0, 1, 2], p=[1/3, 1/3, 1/3])
    return rand

In [ ]:
np.random.seed(4)
print('%d, %d, %d, %d, %d, %d' % (policy(), policy(), policy(), policy(), policy(), policy()))

2, 1, 2, 2, 2, 0


### Question 9

We're going to use numpy to generate random numbers. Check the documentation for numpy.random.choice() to complete the functions below.

NOTE: it's important that you pass the parameters to np.random.choice in order. For example, if the instructions say 'return A with probability A1 and B with probability B1', you should pass the arguments to np.random.choice as np.random.choice([A, B], p=[A1, B1]) to be marked correctly.

In [ ]:
import numpy as np


def policy(p1, p2, p3, p4=0.5):
    # p1, p2, p3 are, respectively, the probabilities of choosing between 1, 2, and 3
    # the default value for p4 should be 0.5
    # action equals 1 with probability p1, 2 with probability p2, and 3 with probability p3
    action = np.random.choice([1, 2, 3], p=[p1, p2, p3])
    # Depending on the value of 'action', we choose one of the following options:
    # if action is 1: return action1()
    # if action is 2: return action2()
    # if action is 3: return action1() with probability p4, and action2() otherwise

    if action == 1: return action1()
    if action == 2: return action2()
    if action == 3:
      val = np.random.choice([action1(), action2()], p=[p4, 1-p4])
      return val

def action1(p=0.2):
    # Return 0 with probability p and 1 otherwise
    # the default value for p should be 0.2
    val = np.random.choice([0, 1], p=[p, 1-p])
    return val

def action2(p=0.9):
    # Return 3 with probability p and -5 otherwise
    # the default value for p should be 0.9
    val = np.random.choice([3, -5], p=[p, 1-p])
    return val

In [ ]:
np.random.seed(4)
# Check default value for p1
pulls = [action1() for _ in range(20000)]
print('%.3f' % np.mean(pulls))

0.794


The array *a* for random.choice **doesn't have to be a number**!

In [ ]:
val = np.random.choice(['hello', 'world'], p=[0.5, 0.5])
print(val)

hello
